version: '3.3'

services:

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle
    volumes:
      - ./moodle_db:/var/lib/mysql

  moodle:
    image: bitnami/moodle:latest
    ports:
      - "8200:8080"
      - "8443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_USERNAME=User
      - MOODLE_PASSWORD=p4ssw0rd
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata  
    depends_on:
      - mariadb          
    links:
      - mariadb:mariadb




  
     
      